### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fastrizwaan** [Windows-On-Linux/Office-On-Linux#2]
`WINEARCH=win32 WINEPREFIX=~/wol/office2013 wine setup.exe` throws this error

![Screenshot from 2022-08-27 12-15-57](https://user-images.githubusercontent.com/1161682/187018585-a11f3fcf-2e9f-4b9f-be9d-9fdc620ad475.png)

**Comment by andreock** [comment]
Try now, I should have fixed
